Feature/10 implementar navigation bar
Santiago9913/MISW4203-Moviles pull request #43
Opened 2024-04-21 06:32 UTC by jcdejesus

**Descripción:**
Implementa componentes UI base para las secciones principales de la app.

**Evidencias:**

https://github.com/Santiago9913/MISW4203-Moviles/assets/142068448/ecd59d31-23c4-42dd-bed0-3b1b0a627c5e

**Tareas pendientes:**
**Con la finalidad de ir integrando lo mas rápido posible al branch principal, en tareas futuras se harán mejoras sobre la UI como por ejemplo:**
**1. Dejar seleccionado el botón del navigation donde se esta ubicado actualmente.**

2024-04-22 03:25 UTC, ccpinzonh1 requested changes
Recomiendo revisar lo de las imagenes y los vectores. 
podemos usar herramientas como https://vectormagic.com/ para estos casos

2024-04-22 03:25 UTC, ccpinzonh1 commented on app/src/main/res/values/strings.xml
> +    <string name="sample">Sample</string>
Question:
Usamos esta variables para algo en especifico?

2024-04-22 03:25 UTC, ccpinzonh1 commented on app/src/main/res/drawable-hdpi/airpods_icons.png
Question:
Podemos usar vectors en vez de imagenes ? Creo que para estos casos es mejor manejar un vector. dado que si necesitamos escalar un vector no se poerde calidad

2024-04-22 12:23 UTC, jcdejesus commented on app/src/main/res/values/strings.xml
> +    <string name="sample">Sample</string>
Corregido en commit d1b999395be3ffa3b97b6d5749841adc43c14005

2024-04-22 12:25 UTC, jcdejesus commented on app/src/main/res/drawable-hdpi/airpods_icons.png
Suena interesante pero poco probable que los botones del navigation bar tengan que escalar. Igual lo tenemos presente si tenemos problemas de rendimiento...

2024-04-23 00:51 UTC, ccpinzonh1 commented on app/src/main/res/drawable-hdpi/airpods_icons.png
Entonces porque tenemos diferentes tamaños para esas imágenes?

2024-04-23 00:53 UTC, ccpinzonh1 approved these changes

2024-04-23 00:53 UTC, jcdejesus commented on app/src/main/res/drawable-hdpi/airpods_icons.png
Por que Android tiene una series de carpeta dependiendo de la resolución de los dispositivos para colocar imagenes...y es una opción nativa de Android para renderizar iconos y texturas.

2024-04-28 03:58 UTC, closed without merging