Feat/skeleton
Santiago9913/MISW4203-Moviles pull request #44
Opened 2024-04-23 20:56 UTC by Santiago9913

2024-04-23 21:11 UTC, jcdejesus requested changes
Por favor agregar videos o imagenes para ver como funciona la nvegacion.

2024-04-23 23:08 UTC, jcdejesus commented
Definir paleta de colores a Utilizar para que todos usemos los colores...y no tengamos la sorpresa de overlaping...

<img width="288" alt="Captura de Pantalla 2024-04-23 a la(s) 6 07 06 p m" src="https://github.com/Santiago9913/MISW4203-Moviles/assets/142068448/d6305a60-ef5f-42eb-b00f-0a780fad054f">

2024-04-23 23:10 UTC, ccpinzonh1 requested changes
Resolver los comentarios de Juan

2024-04-23 23:10 UTC, ccpinzonh1 commented on app/src/main/java/com/grupo3/vinilos/LogIn.kt
> +       }
Podemos optimizar esto en una función?
```suggestion
        LogInButton(navController, "Home", "Visitante")
        LogInButton(navController, "Home?auth=${true}", "Coleccionista")
```
```kotlin
@Composable
fun LogInButton(navController: NavController, route: String, buttonText: String) {
    Button(onClick = { navController.navigate(route) }) {
        Text(text = buttonText)
    }
}
```

2024-04-24 15:45 UTC, Santiago9913 commented on app/src/main/java/com/grupo3/vinilos/LogIn.kt
> +       }
No es una buena optimización, por el hecho de que le estas pasando todo el navController a un componente. Esas funciones siempre deben de estar al nivel de donde se instancia el componente y no en su propio scope

2024-04-24 17:57 UTC, ccpinzonh1 approved these changes

2024-04-24 19:48 UTC, jcdejesus approved these changes

2024-04-24 20:06 UTC, merged