Feat/songs list
Santiago9913/MISW4203-Moviles pull request #60
Opened 2024-05-07 17:43 UTC by Santiago9913

2024-05-07 17:56 UTC, ccpinzonh1 requested changes

2024-05-07 17:56 UTC, ccpinzonh1 commented on app/src/main/java/com/grupo3/vinilos/album/detail/SongsList.kt
> +            Text(text = "CANCIONES NO DISPONIBLES EN EL MOMENTO", style = Typography.titleMedium)
Suggestion: Podemos mover esta cadena al string.xml?

2024-05-07 17:56 UTC, ccpinzonh1 commented on app/src/main/java/com/grupo3/vinilos/album/detail/SongsList.kt
> +                                color = Color("#F5F8FA".toColorInt()),
Question: estos colores los estamos manejando en el Colors.xml?

2024-05-07 17:56 UTC, ccpinzonh1 commented on app/src/main/java/com/grupo3/vinilos/album/detail/SongsList.kt
> +                                        text = song.duration,
Nitpick: podemos ajustar el formato de la duración? Debería ser HH:MM:SS

2024-05-08 17:42 UTC, Santiago9913 commented on app/src/main/java/com/grupo3/vinilos/album/detail/SongsList.kt
> +                                        text = song.duration,
No se si tiene mucho sentido formatearlo, debido a que solo tiene minutos y segundo y no vamos a realizar operaciones con ese valor

2024-05-09 00:22 UTC, ccpinzonh1 commented on app/src/main/java/com/grupo3/vinilos/album/detail/SongsList.kt
> +                                        text = song.duration,
Vale, lo mencionodebido a que asi esta en la HU

2024-05-09 00:27 UTC, ccpinzonh1 commented
Por favor hacer rebase con develop para poder revisar

2024-05-09 02:50 UTC, ccpinzonh1 approved these changes

2024-05-09 02:50 UTC, merged