feat(album): Create album
Santiago9913/MISW4203-Moviles pull request #71
Opened 2024-05-17 20:29 UTC by Santiago9913

2024-05-17 20:55 UTC, ccpinzonh1 requested changes

2024-05-17 20:55 UTC, ccpinzonh1 commented on app/src/main/java/com/grupo3/vinilos/album/service/AlbumService.kt
> +    suspend fun createAlbum(album: AlbumDto): AlbumDto
Question: 
No es necesario el `@Body` para el album ?

2024-05-17 20:55 UTC, ccpinzonh1 commented on app/src/main/java/com/grupo3/vinilos/network/RetroFitInstance.kt
> +
remover linea extra

2024-05-17 20:55 UTC, ccpinzonh1 commented on app/src/main/java/com/grupo3/vinilos/album/list/AlbumsViewModel.kt
> +            repository.createAlbum(album = album);
No deberíamos agregar el album creado al current state?

2024-05-17 20:55 UTC, ccpinzonh1 commented on app/src/main/java/com/grupo3/vinilos/album/list/AlbumsViewModel.kt
> +    suspend fun createAlbum(album: AlbumDto) {
podemos hacer un wrapper de la funcion en un viewModelScope?
```suggestion
    fun createAlbum(album: AlbumDto) {
    viewModelScope.launch(){
```
Para aplicar las recomendaciones del monitor ?

2024-05-17 21:33 UTC, Santiago9913 commented on app/src/main/java/com/grupo3/vinilos/album/service/AlbumService.kt
> +    suspend fun createAlbum(album: AlbumDto): AlbumDto
Sí, se me pasó por completo. Gracias

2024-05-17 21:36 UTC, Santiago9913 commented on app/src/main/java/com/grupo3/vinilos/album/list/AlbumsViewModel.kt
> +    suspend fun createAlbum(album: AlbumDto) {
Creo que ya no es necesario debido a que se esta usando el `Dispatcher.IO` para realizar la operación. Siendo así, la vista es la encargada de llamar la función de la siguiente forma

```kotlin
LaunchedEffect(Unit) {
        withContext(Dispatchers.IO) {
            viewModel.createAlbum(...)
        }
    }
```

2024-05-17 23:53 UTC, ccpinzonh1 commented on app/src/main/java/com/grupo3/vinilos/album/list/AlbumsViewModel.kt
> +    suspend fun createAlbum(album: AlbumDto) {
Y como va a ser lanzada desde el boton ?

2024-05-18 21:40 UTC, Santiago9913 commented on app/src/main/java/com/grupo3/vinilos/album/list/AlbumsViewModel.kt
> +    suspend fun createAlbum(album: AlbumDto) {
Ah, en ese caso igual se puede llamar al dispatcher y cambiar el estado de la pantalla para que se muestre un loading

2024-05-18 21:41 UTC, Santiago9913 commented on app/src/main/java/com/grupo3/vinilos/album/list/AlbumsViewModel.kt
> +            repository.createAlbum(album = album);
No es necesario porque no lo vas a mostrar, se debería de revalidar la query desde la ui para traerse los nuevos cambios

2024-05-18 21:42 UTC, Santiago9913 commented on app/src/main/java/com/grupo3/vinilos/network/RetroFitInstance.kt
> +
Listo, solucionado

2024-05-18 21:45 UTC, Santiago9913 commented on app/src/main/java/com/grupo3/vinilos/album/list/AlbumsViewModel.kt
> +    suspend fun createAlbum(album: AlbumDto) {
Aunque revisando los comentarios del monitor, debería de estar tal y como mencionas Chris. Lo voy a agregar

2024-05-18 22:00 UTC, Santiago9913 commented on app/src/main/java/com/grupo3/vinilos/album/list/AlbumsViewModel.kt
> +    suspend fun createAlbum(album: AlbumDto) {
Reisando, la función ya se puede encapuslar en un viewModelScope desde la vista. Lo marcaré como resuelto

2024-05-18 22:54 UTC, ccpinzonh1 approved these changes

2024-05-19 22:36 UTC, merged